# Generated by Django 5.0.1 on 2024-06-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='0785283918', max_length=12),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(default='default@example.com', max_length=255, null=True),
        ),
    ]
