# Generated by Django 4.2.7 on 2024-06-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_otp_customuser_otp_expiration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_expiration',
        ),
    ]
