# Generated by Django 5.0.1 on 2024-05-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_code', models.CharField(max_length=255)),
                ('farmer_name', models.CharField(max_length=255)),
                ('loan_limit', models.IntegerField()),
                ('loan_amount', models.IntegerField()),
            ],
        ),
    ]
