# Generated by Django 5.0.1 on 2024-05-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_approved',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
