# Generated by Django 5.0.1 on 2024-05-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_loan_total_paid_alter_loan_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_paid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LoanInstallments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_code', models.CharField(max_length=255)),
                ('farmer_name', models.CharField(max_length=255)),
                ('paid_amount', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
            ],
        ),
    ]
