# Generated by Django 5.0.1 on 2024-02-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CherryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(default=None, max_length=20)),
                ('grade_desc', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'cherry_grade',
            },
        ),
        migrations.CreateModel(
            name='Cws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cws_code', models.TextField(default=None, max_length=255)),
                ('cws_name', models.TextField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'cws',
            },
        ),
        migrations.CreateModel(
            name='StationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_limit', models.DecimalField(decimal_places=1, default=0.0, max_digits=10)),
                ('grade', models.CharField(default=None, max_length=20)),
                ('cws', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_settings', to='cws.cws')),
            ],
            options={
                'db_table': 'station_settings',
            },
        ),
    ]
