# Generated by Django 5.0.1 on 2024-02-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cws', '0002_cherrygradeoutput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cherrygradeoutput',
            old_name='grade',
            new_name='grade_id',
        ),
    ]
