# Generated by Django 5.0.1 on 2024-02-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cws', '0003_rename_grade_cherrygradeoutput_grade_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cherrygradeoutput',
            old_name='grade_id',
            new_name='grade',
        ),
    ]
