# Generated by Django 5.0.1 on 2024-02-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cws', '0004_rename_grade_id_cherrygradeoutput_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cherrygradeoutput',
            name='grade_name',
            field=models.CharField(default='CA', max_length=20),
            preserve_default=False,
        ),
    ]
