# Generated by Django 5.0.1 on 2024-04-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cws', '0006_inventoryoutput'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50)),
                ('cherry_grade', models.TextField(max_length=50)),
                ('batch_creation_date', models.DateField()),
                ('harvest_cherry_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_cherry_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_to', models.TextField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'received_harvest',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cws_name', models.TextField(max_length=255)),
                ('cws_code', models.TextField(default='MAC', max_length=255)),
                ('purchase_date', models.DateField()),
                ('farmer_code', models.TextField(max_length=255)),
                ('farmer_name', models.TextField(max_length=255)),
                ('season', models.IntegerField()),
                ('cherry_kg', models.IntegerField()),
                ('has_card', models.IntegerField()),
                ('cherry_grade', models.TextField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grn_no', models.IntegerField()),
                ('transport', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_no', models.TextField(max_length=50)),
                ('occupation', models.TextField(default='Farmer', max_length=255)),
                ('synced', models.IntegerField(default=1, null=True)),
                ('id_no', models.IntegerField(default=0, null=True)),
                ('is_received', models.IntegerField(default=0)),
                ('is_paid', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('plot_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=50, unique=True)),
                ('schedule_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('location_to', models.TextField(max_length=255)),
                ('completed_date', models.DateField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cws.cherrygradeoutput')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='StockInventoryOutputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=50)),
                ('output_quantity', models.IntegerField()),
                ('out_turn', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cws.inventoryoutput')),
            ],
            options={
                'db_table': 'stock_inventory_outputs',
                'unique_together': {('process_name', 'process_type')},
            },
        ),
    ]
