# Generated by Django 5.0.1 on 2024-02-11 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_alter_farmer_created_at_alter_farmer_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_certified',
            field=models.BooleanField(default=True),
        ),
    ]
