# Generated by Django 5.0.1 on 2024-04-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0006_farmerandfarmdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerandfarmdetails',
            name='national_id',
            field=models.TextField(default=0, max_length=20, unique=True),
        ),
    ]
